steps:
  #install
  - name: node:13
    entrypoint: npm
    dir: 'api/'
    args: ['install']
  - name: node:10
    entrypoint: npm
    dir: 'backend/function_process_check_request/'
    args: ['install']
  - name: node:10
    entrypoint: npm
    dir: 'backend/function_process_email_request/'
    args: ['install']
  - name: node:10
    entrypoint: npm
    dir: 'backend/function_process_web_request/'
    args: ['install']

  #download credentials
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'api/'
    args: ['cp', 'gs://email-service-d-settings/.env', '.env']
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'backend/function_process_check_request/'
    args: ['cp', 'gs://email-service-d-settings/.env', '.env']
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'backend/function_process_email_request/'
    args: ['cp', 'gs://email-service-d-settings/.env', '.env']
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'backend/function_process_web_request/'
    args: ['cp', 'gs://email-service-d-settings/.env', '.env']

  #tests
  - name: node:13
    entrypoint: npm
    dir: 'api/'
    args: ['test']
  - name: node:10
    entrypoint: npm
    dir: 'backend/function_process_check_request/'
    args: ['test']
  - name: node:10
    entrypoint: npm
    dir: 'backend/function_process_email_request/'
    args: ['test']
  - name: node:10
    entrypoint: npm
    dir: 'backend/function_process_web_request/'
    args: ['test']

  #deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'api/'
    args:
      - app
      - deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'backend/function_process_check_request/'
    args:
      - functions
      - deploy
      - function_process_check_request
      - --source=.
      - --trigger-topic=topic-check-sendgrid-requests
      - --runtime=nodejs10
      - --entry-point=processCheckRequest
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'backend/function_process_email_request/'
    args:
      - functions
      - deploy
      - function_process_email_request
      - --source=.
      - --trigger-topic=topic-email-requests
      - --runtime=nodejs10
      - --entry-point=processEmailRequest
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'backend/function_process_web_request/'
    args:
      - functions
      - deploy
      - function_process_web_request
      - --source=.
      - --trigger-topic=topic-web-requests
      - --runtime=nodejs10
      - --entry-point=processWebRequest

  #cronjob
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - scheduler
      - jobs
      - delete
      - post_check_msg_to_topic-check-sendgrid-requests
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - scheduler
      - jobs
      - create
      - pubsub
      - post_check_msg_to_topic-check-sendgrid-requests
      - --schedule=* * * * *
      - --topic=topic-check-sendgrid-requests
      - --message-body={}

timeout: "1600s"