steps:
  #install
  - name: node:13
    entrypoint: npm
    dir: 'api/'
    args: ['install']
  - name: node:13
    entrypoint: npm
    dir: 'backend/function_process_check_request'
    args: ['install']
  - name: node:13
    entrypoint: npm
    dir: 'backend/function_process_email_request'
    args: ['install']
  - name: node:13
    entrypoint: npm
    dir: 'backend/function_process_web_request'
    args: ['install']
  #tests
  - name: node:13
    entrypoint: npm
    dir: 'api/'
    args: ['test']
  - name: node:13
    entrypoint: npm
    dir: 'backend/function_process_check_request'
    args: ['test']
  - name: node:13
    entrypoint: npm
    dir: 'backend/function_process_email_request'
    args: ['test']
  - name: node:13
    entrypoint: npm
    dir: 'backend/function_process_web_request'
    args: ['test']
  #deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'api/'
    args: ['app', 'deploy']
      - app
      - deploy
      - --verbosity=debug
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'backend/function_process_check_request'
    args:
      - functions
      - deploy
      - function_process_check_request
      - --source=.
      - --trigger-topic=topic-check-sendgrid-requests
      - --runtime=node13
      - --entry-point=processCheckRequest
      - --verbosity=debug
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'backend/function_process_email_request'
    args:
      - functions
      - deploy
      - function_process_email_request
      - --source=.
      - --trigger-topic=topic-email-requests
      - --runtime=node13
      - --entry-point=processEmailRequest
      - --verbosity=debug
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'backend/function_process_web_request'
    args:
      - functions
      - deploy
      - function_process_web_request
      - --source=.
      - --trigger-topic=topic-web-requests
      - --runtime=node13
      - --entry-point=processWebRequest
      - --verbosity=debug
  #cronjob
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - scheduler
      - jobs
      - create
      - pubsub
      - post_check_msg_to_topic-check-sendgrid-requests
      - --schedule="* * * * *"
      - --topic=topic-check-sendgrid-requests
      - --message-body="no
      - --verbosity=debug

timeout: "1600s"