steps:
  - name: node:13.9.0
    entrypoint: npm
    dir: 'api/'
    args: ['install']
  - name: node:13.9.0
    entrypoint: npm
    dir: 'backend/function_process_check_request'
    args: ['install']
  - name: node:13.9.0
    entrypoint: npm
    dir: 'backend/function_process_email_request'
    args: ['install']
  - name: node:13.9.0
    entrypoint: npm
    dir: 'backend/function_process_web_request'
    args: ['install']

  - name: node:13.9.0
    entrypoint: npm
    dir: 'api/'
    args: ['test']
  - name: node:13.9.0
    entrypoint: npm
    dir: 'backend/function_process_check_request'
    args: ['test']
  - name: node:13.9.0
    entrypoint: npm
    dir: 'backend/function_process_email_request'
    args: ['test']
  - name: node:13.9.0
    entrypoint: npm
    dir: 'backend/function_process_web_request'
    args: ['test']