runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5

liveness_check:
  path: "/health/check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

env_variables:
  TOPIC_WEB_REQUESTS: "topic-web-requests"
  TOPIC_EMAIL_REQUESTS: "topic-email-requests"
  TOPIC_CHECK_SENDGRID_REQUESTS: "topic-check-sendgrid-requests"
  GOOGLE_PROJECT_ID: "email-service-d"