swagger: "2.0"
info:
  description: "Schedules emails to be sent via Sendgrid and keeps track of blocked/spam/bounced emails"
  version: "1.0.0"
  title: "email-service.d"
basePath: "/api"
tags:
  - name: "mail"
schemes:
  - "https"
paths:
  /mail/send:
    post:
      tags:
        - "mail"
      summary: "Send an email"
      description: ""
      operationId: "placeOrder"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/Mail"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/MailResponse"
        401:
          description: "Invalid Auth"
        422:
          description: "Invalid Mail"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "X-AUTH"
    in: "header"
definitions:
  Mail:
    type: "object"
    properties:
      from:
        type: "string"
        format: "email"
      to:
        type: "array"
        items:
          type: "string"
      cc:
        type: "array"
        items:
          type: "string"
      bcc:
        type: "array"
        items:
          type: "string"
      subject:
        type: "string"
      body:
        type: "string"
  MailResponse:
    type: "object"
    properties:
      status:
        type: "string"
      data:
        type: object
        items:
          $ref: '#/definitions/Mail'
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"